// Extrae metadata + subtitulos publicos de un video de YouTube.
// Metodo: la pagina de watch publica incluye un JSON embebido
// (ytInitialPlayerResponse) con la lista de pistas de subtitulos
// publicas (captionTracks) cuando existen. Es el mismo dato que el
// reproductor oficial de YouTube usa para mostrar los subtitulos: no
// hay login, no hay API privada, no hay bypass de nada.

const WATCH_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

class TranscriptError extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
}

async function fetchWithTimeout(url, options, timeoutMs) {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, { ...options, signal: controller.signal });
  } finally {
    clearTimeout(timeoutId);
  }
}

function extractPlayerResponse(html) {
  const marker = "ytInitialPlayerResponse = ";
  const start = html.indexOf(marker);
  if (start === -1) return null;

  const jsonStart = start + marker.length;
  let depth = 0;
  let end = -1;
  for (let i = jsonStart; i < html.length; i++) {
    const ch = html[i];
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) {
        end = i + 1;
        break;
      }
    }
  }
  if (end === -1) return null;

  try {
    return JSON.parse(html.slice(jsonStart, end));
  } catch {
    return null;
  }
}

function pickTrack(tracks, preferredLang) {
  if (preferredLang) {
    const exact = tracks.find((t) => t.languageCode === preferredLang);
    if (exact) return exact;
  }
  const manual = tracks.find((t) => t.kind !== "asr");
  if (manual) return manual;
  return tracks[0];
}

async function fetchSegments(baseUrl) {
  const res = await fetchWithTimeout(
    `${baseUrl}&fmt=json3`,
    { headers: { "User-Agent": WATCH_UA } },
    10000
  );
  if (!res.ok) throw new TranscriptError(502, "No se pudo descargar el subtitulo.");

  const rawText = await res.text();
  if (!rawText) {
    throw new TranscriptError(
      503,
      "YouTube esta bloqueando la extraccion de subtitulos en este momento. Intentalo mas tarde."
    );
  }

  let data;
  try {
    data = JSON.parse(rawText);
  } catch {
    throw new TranscriptError(502, "El formato del subtitulo no es el esperado.");
  }
  const events = data.events || [];
  const segments = [];

  for (const event of events) {
    if (!event.segs || typeof event.tStartMs !== "number") continue;
    const text = event.segs
      .map((s) => s.utf8 || "")
      .join("")
      .replace(/\n/g, " ")
      .trim();
    if (!text) continue;
    segments.push({
      start: event.tStartMs / 1000,
      duration: (event.dDurationMs || 2000) / 1000,
      text,
    });
  }
  return segments;
}

export async function getYoutubeTranscript(videoId, preferredLang) {
  const watchRes = await fetchWithTimeout(
    `https://www.youtube.com/watch?v=${videoId}`,
    {
      headers: {
        "User-Agent": WATCH_UA,
        "Accept-Language": "en-US,en;q=0.9",
      },
    },
    10000
  );

  if (!watchRes.ok) {
    throw new TranscriptError(502, "No se pudo acceder al video.");
  }

  const html = await watchRes.text();
  const playerResponse = extractPlayerResponse(html);
  if (!playerResponse) {
    throw new TranscriptError(502, "No se pudo leer la informacion del video.");
  }

  const status = playerResponse.playabilityStatus?.status;
  if (status === "ERROR") {
    throw new TranscriptError(404, "El video no existe o fue eliminado.");
  }
  if (status === "LOGIN_REQUIRED") {
    throw new TranscriptError(403, "Este video es privado o requiere iniciar sesion.");
  }
  if (status && status !== "OK") {
    throw new TranscriptError(403, "Este video no es accesible.");
  }

  const tracks =
    playerResponse.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!tracks || tracks.length === 0) {
    throw new TranscriptError(404, "Este video no tiene subtitulos publicos.");
  }

  const track = pickTrack(tracks, preferredLang);
  const segments = await fetchSegments(track.baseUrl);
  if (segments.length === 0) {
    throw new TranscriptError(404, "El subtitulo de este video esta vacio.");
  }

  const details = playerResponse.videoDetails || {};
  const thumbnails = (details.thumbnail?.thumbnails || []).map((t) => t.url);
  const fullText = segments.map((s) => s.text).join(" ");

  return {
    platform: "youtube",
    videoId,
    title: details.title || null,
    thumbnails,
    language: track.languageCode,
    languageName: track.name?.simpleText || track.languageCode,
    isAutoGenerated: track.kind === "asr",
    source: track.kind === "asr" ? "speech-to-text" : "native",
    segmentCount: segments.length,
    transcript: segments,
    fullText,
  };
}

export { TranscriptError };
