// Extrae subtitulos publicos de YouTube.
//
// Estrategia:
//   1. Si TRANSCRIPT_SERVICE_URL esta configurado, delega en el
//      microservicio Python (youtube-transcript-api). Es el camino
//      fiable hoy: la libreria resuelve PoToken y demas bloqueos.
//   2. Si no, intenta Innertube ANDROID/IOS/WEB como fallback.

class TranscriptError extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
}

async function fetchWithTimeout(url, options, timeoutMs) {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, { ...options, signal: controller.signal });
  } finally {
    clearTimeout(timeoutId);
  }
}

async function viaTranscriptService(videoId, preferredLang, serviceUrl) {
  const url = new URL(`${serviceUrl.replace(/\/$/, "")}/transcript`);
  url.searchParams.set("video_id", videoId);
  if (preferredLang) url.searchParams.set("lang", preferredLang);

  console.log("[viaTranscriptService] GET", url.toString());
  const res = await fetchWithTimeout(url.toString(), { method: "GET" }, 20000);
  const text = await res.text();

  if (!res.ok) {
    let detail = text;
    try {
      const parsed = JSON.parse(text);
      detail = parsed.detail || parsed.error || text;
    } catch {}
    console.log("[viaTranscriptService] HTTP", res.status, detail);
    throw new TranscriptError(
      res.status,
      detail || "Error en el servicio de transcripts."
    );
  }

  let data;
  try {
    data = JSON.parse(text);
  } catch {
    throw new TranscriptError(
      502,
      "El servicio de transcripts devolvio JSON invalido."
    );
  }

  return {
    platform: "youtube",
    videoId: data.videoId || videoId,
    title: data.title || null,
    author: data.author || null,
    thumbnails: Array.isArray(data.thumbnails) ? data.thumbnails : [],
    language: data.language || null,
    languageName: data.languageName || data.language || null,
    isAutoGenerated: Boolean(data.isAutoGenerated),
    source: data.isAutoGenerated ? "speech-to-text" : "native",
    segmentCount:
      data.segmentCount ?? (data.transcript ? data.transcript.length : 0),
    transcript: data.transcript || [],
    fullText: data.fullText || "",
  };
}

const INNERTUBE_API_KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8";
const WATCH_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";
const ANDROID_UA =
  "com.google.android.youtube/19.09.37 (Linux; U; Android 11) gzip";
const IOS_UA =
  "com.google.ios.youtube/19.09.3 (iPhone16,2; U; CPU iOS 17_4 like Mac OS X)";

async function innertubePlayer(
  videoId,
  clientName,
  clientVersion,
  userAgent,
  extraClient = {}
) {
  const body = {
    context: {
      client: {
        clientName,
        clientVersion,
        hl: "en",
        gl: "US",
        userAgent,
        ...extraClient,
      },
    },
    videoId,
    contentCheckOk: true,
    racyCheckOk: true,
  };

  const res = await fetchWithTimeout(
    `https://www.youtube.com/youtubei/v1/player?key=${INNERTUBE_API_KEY}&prettyPrint=false`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "User-Agent": userAgent,
      },
      body: JSON.stringify(body),
    },
    10000
  );

  if (!res.ok) return null;
  try {
    return await res.json();
  } catch {
    return null;
  }
}

function pickTrack(tracks, preferredLang) {
  if (!tracks || tracks.length === 0) return null;
  if (preferredLang) {
    const exact = tracks.find((t) => t.languageCode === preferredLang);
    if (exact) return exact;
  }
  const manual = tracks.find((t) => t.kind !== "asr");
  return manual || tracks[0];
}

async function fetchSegments(baseUrl, clientName) {
  const suffix =
    clientName === "ANDROID"
      ? "&fmt=json3&c=ANDROID&cver=19.09.37"
      : clientName === "IOS"
      ? "&fmt=json3&c=IOS&cver=19.09.3"
      : "&fmt=json3";

  const urls = [
    `${baseUrl}${baseUrl.includes("?") ? "" : "?"}${suffix}`,
    `${baseUrl}&fmt=json3`,
  ];

  for (const u of urls) {
    try {
      const res = await fetchWithTimeout(
        u,
        { headers: { "User-Agent": WATCH_UA } },
        10000
      );
      if (!res.ok) continue;
      const raw = await res.text();
      if (!raw.trim()) continue;
      let data;
      try {
        data = JSON.parse(raw);
      } catch {
        continue;
      }
      const events = data.events || [];
      const segments = [];
      for (const ev of events) {
        if (!ev.segs || typeof ev.tStartMs !== "number") continue;
        const text = ev.segs
          .map((s) => s.utf8 || "")
          .join("")
          .replace(/\n/g, " ")
          .trim();
        if (!text) continue;
        segments.push({
          start: ev.tStartMs / 1000,
          duration: (ev.dDurationMs || 2000) / 1000,
          text,
        });
      }
      if (segments.length > 0) return segments;
    } catch {
      continue;
    }
  }
  return [];
}

function mapPlayability(status) {
  if (status === "ERROR")
    return new TranscriptError(404, "El video no existe o fue eliminado.");
  if (status === "LOGIN_REQUIRED")
    return new TranscriptError(403, "Este video requiere iniciar sesion.");
  if (status === "UNPLAYABLE")
    return new TranscriptError(
      403,
      "Este video no se puede reproducir en tu region."
    );
  if (status && status !== "OK")
    return new TranscriptError(403, `Video no accesible (${status}).`);
  return null;
}

async function viaInnertube(videoId, preferredLang) {
  const clients = [
    {
      name: "ANDROID",
      version: "19.09.37",
      ua: ANDROID_UA,
      extra: { androidSdkVersion: 30 },
    },
    {
      name: "IOS",
      version: "19.09.3",
      ua: IOS_UA,
      extra: { deviceModel: "iPhone16,2" },
    },
    { name: "WEB", version: "2.20240101.00.00", ua: WATCH_UA, extra: {} },
  ];

  let lastResp = null;
  for (const c of clients) {
    const resp = await innertubePlayer(
      videoId,
      c.name,
      c.version,
      c.ua,
      c.extra
    );
    if (!resp) continue;
    lastResp = resp;
    const tracks =
      resp?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
    if (!tracks || tracks.length === 0) continue;

    const playabilityErr = mapPlayability(resp?.playabilityStatus?.status);
    if (playabilityErr) throw playabilityErr;

    const track = pickTrack(tracks, preferredLang);
    if (!track?.baseUrl) continue;

    const segments = await fetchSegments(track.baseUrl, c.name);
    if (segments.length === 0) {
      console.log(
        "[viaInnertube]",
        c.name,
        "returned empty segments (PoToken block)"
      );
      continue;
    }

    const details = resp.videoDetails || {};
    return {
      platform: "youtube",
      videoId,
      title: details.title || null,
      author: details.author || null,
      thumbnails: (details.thumbnail?.thumbnails || []).map((t) => t.url),
      language: track.languageCode,
      languageName: track.name?.simpleText || track.languageCode,
      isAutoGenerated: track.kind === "asr",
      source: track.kind === "asr" ? "speech-to-text" : "native",
      segmentCount: segments.length,
      transcript: segments,
      fullText: segments.map((s) => s.text).join(" "),
    };
  }

  if (lastResp) {
    const playabilityErr = mapPlayability(lastResp?.playabilityStatus?.status);
    if (playabilityErr) throw playabilityErr;
    const tracks =
      lastResp?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
    if (!tracks || tracks.length === 0) {
      throw new TranscriptError(404, "Este video no tiene subtitulos publicos.");
    }
  }

  throw new TranscriptError(
    503,
    "YouTube bloqueo la descarga del subtitulo desde el Worker. Configura TRANSCRIPT_SERVICE_URL para usar el microservicio Python."
  );
}

export async function getYoutubeTranscript(videoId, preferredLang, env = {}) {
  const serviceUrl = env.TRANSCRIPT_SERVICE_URL;

  if (serviceUrl) {
    try {
      return await viaTranscriptService(videoId, preferredLang, serviceUrl);
    } catch (err) {
      if (err instanceof TranscriptError) {
        if (err.status !== 502 && err.status !== 500) throw err;
        console.log(
          "[getYoutubeTranscript] service failed, falling back to Innertube:",
          err.message
        );
      } else {
        console.log(
          "[getYoutubeTranscript] service threw, falling back:",
          err.message
        );
      }
    }
  }

  return await viaInnertube(videoId, preferredLang);
}

export { TranscriptError };