"""
Microservicio que envuelve youtube-transcript-api (v1.2.x).
El Worker de Cloudflare le hace fetch() y devuelve el JSON al frontend.

Ejecutar en local:
    pip install -r requirements.txt
    uvicorn app:app --host 0.0.0.0 --port 8000 --reload
"""

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import (
    TranscriptsDisabled,
    NoTranscriptFound,
    VideoUnavailable,
    VideoUnplayable,
)
import logging
import urllib.request
import json

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("transcript-service")

app = FastAPI(title="yt-transcript-service")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET"],
    allow_headers=["*"],
)


def fetch_youtube_oembed(video_id: str):
    """
    Devuelve titulo, autor y miniatura publicos via oEmbed oficial de
    YouTube. No requiere API key ni autenticacion.
    """
    url = (
        f"https://www.youtube.com/oembed"
        f"?url=https://www.youtube.com/watch?v={video_id}&format=json"
    )
    try:
        req = urllib.request.Request(
            url,
            headers={
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/124.0.0.0 Safari/537.36"
            },
        )
        with urllib.request.urlopen(req, timeout=8) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        return {
            "title": data.get("title"),
            "author": data.get("author_name"),
            "thumbnail": data.get("thumbnail_url"),
        }
    except Exception as e:
        logger.warning("oembed failed for %s: %s", video_id, e)
        return {"title": None, "author": None, "thumbnail": None}


def build_thumbnails(video_id: str, thumbnail_url: str | None) -> list[str]:
    """
    Devuelve miniaturas ordenadas de MEJOR a PEOR calidad. El frontend
    usa thumbnails[0] como principal. Si no existe maxresdefault,
    mostrara hqdefault y el navegador hara fallback si la imagen falla.
    """
    candidates = []
    # La que devuelve oEmbed suele ser hqdefault (480x360), fiable.
    if thumbnail_url:
        candidates.append(thumbnail_url)
    # Variantes estandar, de mayor a menor:
    candidates.append(f"https://i.ytimg.com/vi/{video_id}/maxresdefault.jpg")
    candidates.append(f"https://i.ytimg.com/vi/{video_id}/sddefault.jpg")
    candidates.append(f"https://i.ytimg.com/vi/{video_id}/hqdefault.jpg")
    candidates.append(f"https://i.ytimg.com/vi/{video_id}/mqdefault.jpg")
    # Sin duplicados manteniendo el orden de insercion.
    seen = set()
    out = []
    for u in candidates:
        if u and u not in seen:
            seen.add(u)
            out.append(u)
    return out


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/transcript")
def transcript(
    video_id: str = Query(..., min_length=11, max_length=11),
    lang: str = Query(None),
):
    logger.info("request video_id=%s lang=%s", video_id, lang)
    try:
        api = YouTubeTranscriptApi()
        transcript_list = api.list(video_id)

        chosen = None
        if lang:
            for t in transcript_list:
                if t.language_code == lang:
                    chosen = t
                    break

        if chosen is None:
            try:
                chosen = transcript_list.find_manually_created_transcript(["es", "en"])
            except Exception:
                pass

        if chosen is None:
            try:
                chosen = transcript_list.find_generated_transcript(["es", "en"])
            except Exception:
                pass

        if chosen is None:
            for t in transcript_list:
                chosen = t
                break

        if chosen is None:
            raise HTTPException(status_code=404, detail="No hay subtitulos publicos.")

        fetched = chosen.fetch()
        segments = [
            {
                "start": s.start,
                "duration": s.duration,
                "text": s.text.replace("\n", " ").strip(),
            }
            for s in fetched
            if s.text and s.text.strip()
        ]

        full_text = " ".join(s["text"] for s in segments)

        meta = fetch_youtube_oembed(video_id)
        thumbnails = build_thumbnails(video_id, meta["thumbnail"])

        return {
            "videoId": video_id,
            "title": meta["title"],
            "author": meta["author"],
            "thumbnails": thumbnails,
            "language": chosen.language_code,
            "languageName": getattr(chosen, "language", chosen.language_code),
            "isAutoGenerated": chosen.is_generated,
            "segmentCount": len(segments),
            "transcript": segments,
            "fullText": full_text,
        }

    except TranscriptsDisabled:
        raise HTTPException(status_code=404, detail="Subtitulos desactivados para este video.")
    except NoTranscriptFound:
        raise HTTPException(status_code=404, detail="No se encontro ninguna pista de subtitulos.")
    except VideoUnavailable:
        raise HTTPException(status_code=404, detail="El video no existe o fue eliminado.")
    except VideoUnplayable as e:
        raise HTTPException(status_code=403, detail=f"El video no es reproducible: {e}")
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("error inesperado")
        raise HTTPException(status_code=500, detail=f"Error inesperado: {e}")