import { useMemo, useState } from "react";
import {
  Copy,
  Check,
  FileText,
  FileJson,
  FileType,
  Clock,
  Type,
} from "lucide-react";
import BorderBeam from "./BorderBeam";

function formatTimestamp(seconds) {
  const s = Math.floor(seconds);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  const pad = (n) => String(n).padStart(2, "0");
  return h > 0 ? `${pad(h)}:${pad(m)}:${pad(sec)}` : `${pad(m)}:${pad(sec)}`;
}

function toSrt(segments) {
  const srtTime = (sec) => {
    const ms = Math.round((sec % 1) * 1000);
    const total = Math.floor(sec);
    const h = Math.floor(total / 3600);
    const m = Math.floor((total % 3600) / 60);
    const s = total % 60;
    const pad = (n, l = 2) => String(n).padStart(l, "0");
    return `${pad(h)}:${pad(m)}:${pad(s)},${pad(ms, 3)}`;
  };

  return segments
    .map((seg, i) => {
      const start = srtTime(seg.start);
      const end = srtTime(seg.start + (seg.duration || 2));
      return `${i + 1}\n${start} --> ${end}\n${seg.text}\n`;
    })
    .join("\n");
}

function toVtt(segments) {
  const vttTime = (sec) => {
    const ms = Math.round((sec % 1) * 1000);
    const total = Math.floor(sec);
    const h = Math.floor(total / 3600);
    const m = Math.floor((total % 3600) / 60);
    const s = total % 60;
    const pad = (n, l = 2) => String(n).padStart(l, "0");
    return `${pad(h)}:${pad(m)}:${pad(s)}.${pad(ms, 3)}`;
  };

  const body = segments
    .map((seg) => {
      const start = vttTime(seg.start);
      const end = vttTime(seg.start + (seg.duration || 2));
      return `${start} --> ${end}\n${seg.text}\n`;
    })
    .join("\n");

  return `WEBVTT\n\n${body}`;
}

function toMarkdown(data) {
  const lines = data.transcript
    .map((seg) => `**${formatTimestamp(seg.start)}** — ${seg.text}`)
    .join("\n\n");

  return `# ${data.title || data.videoId}\n\n> Transcripcion (${data.languageName}${
    data.isAutoGenerated ? ", autogenerada" : ""
  }) — [youtube.com/watch?v=${data.videoId}](https://youtube.com/watch?v=${data.videoId})\n\n${lines}\n`;
}

function toTimestampedText(segments) {
  return segments
    .map((seg) => `[${formatTimestamp(seg.start)}] ${seg.text}`)
    .join("\n");
}

function download(filename, content, mime = "text/plain") {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function ActionButton({ icon: Icon, label, done, onClick }) {
  return (
    <button
      onClick={onClick}
      className="flex items-center gap-1.5 rounded-lg border border-[#232330] px-3 py-2 font-mono text-xs text-[#8a8a99] transition-colors hover:border-[#f5a623] hover:text-[#f5a623]"
    >
      {done ? (
        <Check size={13} className="text-[#5eead4]" />
      ) : (
        <Icon size={13} />
      )}
      {done ? "hecho" : label}
    </button>
  );
}

export default function TranscriptViewer({ data }) {
  const [query, setQuery] = useState("");
  const [view, setView] = useState("timestamps"); // "timestamps" | "plain"
  const [doneKey, setDoneKey] = useState(null);
  const [copiedLine, setCopiedLine] = useState(null);

  const filteredSegments = useMemo(() => {
    if (!query.trim()) return data.transcript;
    const q = query.toLowerCase();
    return data.transcript.filter((s) => s.text.toLowerCase().includes(q));
  }, [query, data.transcript]);

  const flash = (key) => {
    setDoneKey(key);
    setTimeout(() => setDoneKey((k) => (k === key ? null : k)), 1500);
  };

  const copyToClipboard = async (text, key) => {
    await navigator.clipboard.writeText(text);
    flash(key);
  };

  const copyLine = async (seg, i) => {
    await navigator.clipboard.writeText(seg.text);
    setCopiedLine(i);
    setTimeout(() => setCopiedLine((c) => (c === i ? null : c)), 1200);
  };

  return (
    <div className="relative w-full max-w-3xl rounded-2xl border border-[#232330] bg-[#13131a]">
      <BorderBeam />

      <div className="flex flex-col gap-1 border-b border-[#232330] p-5">
        <h3 className="font-display text-lg text-[#e4e4ea]">
          {data.title || "Transcripcion"}
        </h3>
        <div className="flex flex-wrap items-center gap-3 text-xs font-mono text-[#8a8a99]">
          <span>{data.videoId}</span>
          <span className="text-[#f5a623]">
            {data.languageName} ({data.language})
          </span>
          {data.isAutoGenerated && (
            <span className="rounded border border-[#232330] px-1.5 py-0.5">
              auto-generados — puede tener errores ortograficos
            </span>
          )}
          <span>{data.segmentCount} segmentos</span>
        </div>
      </div>

      <div className="flex items-center gap-2 border-b border-[#232330] p-4">
        <input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Buscar en la transcripcion..."
          className="min-w-[140px] flex-1 rounded-lg border border-[#232330] bg-[#0d0d13] px-3 py-2 text-sm text-[#e4e4ea] placeholder:text-[#5a5a68] outline-none focus:border-[#f5a623]"
        />

        <div className="flex shrink-0 overflow-hidden rounded-lg border border-[#232330] font-mono text-xs">
          <button
            onClick={() => setView("timestamps")}
            title="Vista con timestamps"
            className={`px-2.5 py-2 transition-colors ${
              view === "timestamps"
                ? "bg-[#f5a623] text-[#0a0a0f]"
                : "text-[#8a8a99] hover:bg-[#1a1a23]"
            }`}
          >
            <Clock size={14} />
          </button>
          <button
            onClick={() => setView("plain")}
            title="Vista texto plano"
            className={`px-2.5 py-2 transition-colors ${
              view === "plain"
                ? "bg-[#f5a623] text-[#0a0a0f]"
                : "text-[#8a8a99] hover:bg-[#1a1a23]"
            }`}
          >
            <Type size={14} />
          </button>
        </div>
      </div>

      <div className="flex flex-col gap-2.5 border-b border-[#232330] p-4">
        <div className="flex flex-wrap items-center gap-2">
          <span className="w-full font-mono text-[10px] uppercase tracking-widest text-[#5a5a68] sm:w-auto">
            copiar
          </span>
          <ActionButton
            icon={Copy}
            label="texto plano"
            done={doneKey === "copy-plain"}
            onClick={() => copyToClipboard(data.fullText, "copy-plain")}
          />
          <ActionButton
            icon={Clock}
            label="con timestamps"
            done={doneKey === "copy-ts"}
            onClick={() =>
              copyToClipboard(toTimestampedText(data.transcript), "copy-ts")
            }
          />
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <span className="w-full font-mono text-[10px] uppercase tracking-widest text-[#5a5a68] sm:w-auto">
            descargar
          </span>
          <ActionButton
            icon={FileText}
            label=".txt"
            done={doneKey === "dl-txt"}
            onClick={() => {
              download(`${data.videoId}.txt`, data.fullText, "text/plain");
              flash("dl-txt");
            }}
          />
          <ActionButton
            icon={FileType}
            label=".srt"
            done={doneKey === "dl-srt"}
            onClick={() => {
              download(
                `${data.videoId}.srt`,
                toSrt(data.transcript),
                "application/x-subrip"
              );
              flash("dl-srt");
            }}
          />
          <ActionButton
            icon={FileType}
            label=".vtt"
            done={doneKey === "dl-vtt"}
            onClick={() => {
              download(`${data.videoId}.vtt`, toVtt(data.transcript), "text/vtt");
              flash("dl-vtt");
            }}
          />
          <ActionButton
            icon={FileText}
            label=".md"
            done={doneKey === "dl-md"}
            onClick={() => {
              download(
                `${data.videoId}.md`,
                toMarkdown(data),
                "text/markdown"
              );
              flash("dl-md");
            }}
          />
          <ActionButton
            icon={FileJson}
            label=".json"
            done={doneKey === "dl-json"}
            onClick={() => {
              download(
                `${data.videoId}.json`,
                JSON.stringify(data, null, 2),
                "application/json"
              );
              flash("dl-json");
            }}
          />
        </div>
      </div>

      <div className="group/list max-h-[420px] overflow-y-auto p-5">
        {view === "plain" ? (
          <p className="text-sm leading-relaxed text-[#c8c8d0]">
            {data.fullText}
          </p>
        ) : (
          <div className="flex flex-col gap-1">
            {filteredSegments.map((seg, i) => (
              <div
                key={i}
                className="group flex items-start gap-3 rounded-lg px-2 py-1.5 text-sm transition-colors hover:bg-[#1a1a23]"
              >
                <span className="shrink-0 font-mono text-xs text-[#f5a623] pt-0.5">
                  {formatTimestamp(seg.start)}
                </span>
                <span className="flex-1 text-[#c8c8d0]">{seg.text}</span>
                <button
                  onClick={() => copyLine(seg, i)}
                  title="Copiar esta linea"
                  className="shrink-0 rounded p-1 text-[#5a5a68] opacity-0 transition-opacity hover:text-[#f5a623] group-hover:opacity-100"
                >
                  {copiedLine === i ? (
                    <Check size={13} className="text-[#5eead4]" />
                  ) : (
                    <Copy size={13} />
                  )}
                </button>
              </div>
            ))}
            {filteredSegments.length === 0 && (
              <p className="text-sm text-[#5a5a68]">
                Sin coincidencias para "{query}".
              </p>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
